// <auto-generated />
using EcoPulseBackend.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoPulseBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222094641_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoPulseBackend.Models.SingleEmissionSource.SingleEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AvgExitSpeed")
                        .HasColumnType("real");

                    b.Property<float>("DiameterSource")
                        .HasColumnType("real");

                    b.Property<float>("EjectedTemp")
                        .HasColumnType("real");

                    b.Property<float>("HeightSource")
                        .HasColumnType("real");

                    b.Property<int>("SedimentationRateRatio")
                        .HasColumnType("integer");

                    b.Property<int>("TempStratificationRatio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SingleEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TrafficLightCycles")
                        .HasColumnType("integer");

                    b.Property<float>("TrafficLightStopTime")
                        .HasColumnType("real");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<int>("VehiclesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TrafficLightQueueEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleFlowEmissionSource.VehicleFlowEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AverageSpeed")
                        .HasColumnType("real");

                    b.Property<float>("MaxTrafficIntensity")
                        .HasColumnType("real");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VehicleFlowEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.SingleEmissionSource.SingleEmissionSource", b =>
                {
                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("SingleEmissionSourceId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("Lat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("Lon");

                            b1.HasKey("SingleEmissionSourceId");

                            b1.ToTable("SingleEmissionSources");

                            b1.WithOwner()
                                .HasForeignKey("SingleEmissionSourceId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("TrafficLightQueueEmissionSourceId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("Lat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("Lon");

                            b1.HasKey("TrafficLightQueueEmissionSourceId");

                            b1.ToTable("TrafficLightQueueEmissionSources");

                            b1.WithOwner()
                                .HasForeignKey("TrafficLightQueueEmissionSourceId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleFlowEmissionSource.VehicleFlowEmissionSource", b =>
                {
                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "EndLocation", b1 =>
                        {
                            b1.Property<int>("VehicleFlowEmissionSourceId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("EndLat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("EndLon");

                            b1.HasKey("VehicleFlowEmissionSourceId");

                            b1.ToTable("VehicleFlowEmissionSources");

                            b1.WithOwner()
                                .HasForeignKey("VehicleFlowEmissionSourceId");
                        });

                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "StartLocation", b1 =>
                        {
                            b1.Property<int>("VehicleFlowEmissionSourceId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("StartLat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("StartLon");

                            b1.HasKey("VehicleFlowEmissionSourceId");

                            b1.ToTable("VehicleFlowEmissionSources");

                            b1.WithOwner()
                                .HasForeignKey("VehicleFlowEmissionSourceId");
                        });

                    b.Navigation("EndLocation")
                        .IsRequired();

                    b.Navigation("StartLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
