// <auto-generated />
using EcoPulseBackend.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoPulseBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224101530_AddCityToSources")]
    partial class AddCityToSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoPulseBackend.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.SingleEmissionSource.SingleEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AvgExitSpeed")
                        .HasColumnType("real");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<float>("DiameterSource")
                        .HasColumnType("real");

                    b.Property<float>("EjectedTemp")
                        .HasColumnType("real");

                    b.Property<float>("HeightSource")
                        .HasColumnType("real");

                    b.Property<int>("SedimentationRateRatio")
                        .HasColumnType("integer");

                    b.Property<int>("TempStratificationRatio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("SingleEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueue.VehicleGroupQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TrafficLightQueueEmissionSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<int>("VehiclesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrafficLightQueueEmissionSourceId");

                    b.ToTable("VehicleGroupQueues");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("TrafficLightCycles")
                        .HasColumnType("integer");

                    b.Property<float>("TrafficLightStopTime")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TrafficLightQueueEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleFlowEmissionSource.VehicleFlowEmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AverageSpeed")
                        .HasColumnType("real");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<float>("MaxTrafficIntensity")
                        .HasColumnType("real");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("VehicleFlowEmissionSources");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.City", b =>
                {
                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("CityId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("Lat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("Lon");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.SingleEmissionSource.SingleEmissionSource", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("SingleEmissionSourceId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("Lat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("Lon");

                            b1.HasKey("SingleEmissionSourceId");

                            b1.ToTable("SingleEmissionSources");

                            b1.WithOwner()
                                .HasForeignKey("SingleEmissionSourceId");
                        });

                    b.Navigation("City");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueue.VehicleGroupQueue", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", null)
                        .WithMany("VehicleGroups")
                        .HasForeignKey("TrafficLightQueueEmissionSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EcoPulseBackend.Models.Coordinates", "Location", b1 =>
                        {
                            b1.Property<int>("TrafficLightQueueEmissionSourceId")
                                .HasColumnType("integer");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision")
                                .HasColumnName("Lat");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision")
                                .HasColumnName("Lon");

                            b1.HasKey("TrafficLightQueueEmissionSourceId");

                            b1.ToTable("TrafficLightQueueEmissionSources");

                            b1.WithOwner()
                                .HasForeignKey("TrafficLightQueueEmissionSourceId");
                        });

                    b.Navigation("City");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoPulseBackend.Models.VehicleFlowEmissionSource.VehicleFlowEmissionSource", b =>
                {
                    b.HasOne("EcoPulseBackend.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EcoPulseBackend.Models.TrafficLightQueueEmissionSource.TrafficLightQueueEmissionSource", b =>
                {
                    b.Navigation("VehicleGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
