FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["EcoPulseBackend/EcoPulseBackend.csproj", "EcoPulseBackend/"]
RUN dotnet restore "EcoPulseBackend/EcoPulseBackend.csproj"
COPY . .
WORKDIR "/src/EcoPulseBackend"
RUN dotnet build "./EcoPulseBackend.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./EcoPulseBackend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EcoPulseBackend.dll"]
